### ISSUE TITLE
Workflow/To-Do needs to be created

### ISSUE THREAD

**Issue by AetherUnbound** [stoutput/CIS-TronScript-Toolbox#1]
Ben, please create a workflow or To-Do so that we can know what needs to be completed on this project.

**Comment by stoutput** [comment]
Will do ASAP

On Wed, Nov 25, 2015 at 6:23 PM -0800, "Matthew Bowden" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ben, please create a workflow or To-Do so that we can know what needs to be completed on this project.

##

**Comment by AetherUnbound** [comment]
Thank you. Nate is currently working on the checkboxes for selecting modules, but I'd love to know what else can be done!

**Comment by stoutput** [comment]
Okay sweet. In the meantime you could test out TronScript and see what functionality would be useful to us without breaking anything, as well as how to recursively run scans and keep track of objects found/removed.

On Wed, Nov 25, 2015 at 7:34 PM -0800, "Matthew Bowden" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you. Nate is currently working on the checkboxes for selecting modules, but I'd love to know what else can be done!

##

**Comment by stoutput** [comment]
Workflow created
